### ISSUE TITLE
"Expected URI object or URI string" error on itemLink node

### ISSUE THREAD

**Issue by calebwise** [dewyze/dato_dast#3]
I have a simple test page in Middleman:
```
<% @feature_page = dato.find(123) %>
<%= DatoDast.structured_text(@feature_page.content) %>
```
The structured text field in Dato:
![image](https://user-images.githubusercontent.com/2764809/195852741-63a0de58-6877-4578-9617-123161f699c1.png)

In the project, if this was a `link` type, the paragraph and link would render correctly. If the field instead includes a link to a record, with a `itemLink` type, the page doesn't render.

In `config.rb`, in a blank configuration or the following:
```
activate :dato_dast do |config|
  config.item_links = {
    "venue" => "venue_permalink",
  }
end
```
I get the following traceback (extract):
```
ArgumentError: bad argument (expected URI object or URI string)
/Users/caleb/.rbenv/versions/3.1.0/lib/ruby/3.1.0/uri/common.rb:694:in `URI'
/Users/caleb/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/dato_dast-0.2.0/lib/dato_dast/nodes/link.rb:35:in `uri'
/Users/caleb/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/dato_dast-0.2.0/lib/dato_dast/nodes/link.rb:53:in `local_url'
/Users/caleb/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/dato_dast-0.2.0/lib/dato_dast/nodes/link.rb:29:in `path'
```
I get the same bad argument if I replace the simple configuration above with say an [inline item documented](https://github.com/dewyze/dato_dast#value).

I've reproduced on Middleman 4.3.11 (Ruby 3.1.0) and Middleman 4.2 (Ruby 2.7.1).

Many thanks in review.

**Comment by dewyze** [comment]
Can you share the link data about the object you're trying to link? The code there assumes a string.

I've tried a bunch of things and really any string will work. Is there any chance your `venue_permalink` is nil or a number?

```ruby
irb(main):006:0> URI("foo")
=> #<URI::Generic foo>
irb(main):007:0> URI("http:/foo")
=> #<URI::HTTP http:/foo>
irb(main):008:0> URI("http:foo")
=> #<URI::HTTP http:foo>
irb(main):009:0> URI("http://foo")
=> #<URI::HTTP http://foo>
irb(main):010:0> URI("owneur230ur023")
=> #<URI::Generic owneur230ur023>
irb(main):011:0> URI("https://foo")
=> #<URI::HTTPS https://foo>
irb(main):012:0> URI(2)
/Users/john/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/uri/common.rb:694:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
        from (irb):12:in `<main>'
        from bin/console:15:in `<main>'
irb(main):013:0> URI(nil)
/Users/john/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/uri/common.rb:694:in `URI': bad argument (expected URI object or URI string) (ArgumentError)
        from (irb):13:in `<main>'
        from bin/console:15:in `<main>'
```

If it's a number, it's possible I have a subtle bug and need to call `.to_s` or something, but I think more data to be able to be sure.

**Comment by calebwise** [comment]
Hope this helps:

```
{
  "data": {
    "post": {
      "content": {
        "links": [
          {
            "id": "120753404",
            "venuePermalink": "valleyfield"
          }
        ],
        "value": {
          "schema": "dast",
          "document": {
            "type": "root",
            "children": [
              {
                "type": "paragraph",
                "children": [
                  {
                    "type": "span",
                    "value": "This "
                  },
                  {
                    "item": "120753404",
                    "type": "itemLink",
                    "children": [
                      {
                        "type": "span",
                        "value": "links to a record"
                      }
                    ]
                  },
                  {
                    "type": "span",
                    "value": "."
                  }
                ]
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by dewyze** [comment]
I haven't figured out why, but one thing I notice is that your `links` section doesn't have `item_type` (or `itemType`) which is [used in the configuration to know what method to look at](https://github.com/dewyze/dato_dast/blob/main/lib/dato_dast/nodes/item_link.rb#L22-L26). (You'll also notice my `TODO` to handle this situation better with a proper error or something. My Apologies.)

Are you using the datocms ruby gem, or getting the data another way?

**Comment by calebwise** [comment]
If the clarification helps, the data shown was from the CDA explorer within the DatoCMS admin.

I'm using their [middleman-dato](https://github.com/datocms/middleman-dato) gem to get data.

**Comment by dewyze** [comment]
I am also using middleman-dato, what version are you using? Because when I get an item that has structured text, all of my `links` have an `item_type` as well.

```ruby
 :links=>
  [{:id=>"91562779",
    :item_type=>"page",
    :updated_at=>2022-06-14 16:09:40.111 UTC,
    :created_at=>2021-12-28 02:58:50.32 UTC,
    :title=>"My Page Title",
    :slug=>"live",
  }]
```

**Comment by calebwise** [comment]
Hmm ok. I'm on version 0.10.0.

**Comment by dewyze** [comment]
I'm on 0.9.0, but nothing I see in the changelog makes it seem like that would make a difference. I wonder if this is worth a question in the datocms forums, and link this issue?

Without the `item_type` field, we have no idea what field you would look up to grab a URL.

**Comment by calebwise** [comment]
Thanks for your efforts, much appreciated. I think you're right I'll need to pose a question to Dato. Glad we've got a focus area to go off. Thanks.

**Comment by dewyze** [comment]
@calebwise out of curiosity, did you make any progress on this? I'm happy to keep helping, but as long as we're both getting back different values, I'm not sure how else I can help.
